# Generated by Django 3.0.8 on 2020-07-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_rus', models.TextField(blank=True, verbose_name='Описание на русском')),
                ('desc_eng', models.TextField(blank=True, verbose_name='Описание на английском')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('telegram_nick', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Данные о владельце',
                'verbose_name_plural': 'Данные о владельце',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок тэга')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='UniversitySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название предмета')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Тело поста')),
                ('date_pubs', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='main.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='subjects/files', verbose_name='Файл')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='main.UniversitySubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
